version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - ./db_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env